[package]
name = "proto-hal-build"
version = "0.1.0"
edition = "2024"

[dependencies]
ir = { path = "../ir" }
colored = "3.0.0"
proc-macro2 = "1.0.101"
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
quote = "1.0.41"
